# This is a basic workflow to help you get started with Actions

name: Update Website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "source" branch
  push:
    branches: [ "source" ]
  pull_request:
    branches: [ "source" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      - name: echo
        run: echo ${{ github.repository }}
      - name: clone
        run: git clone https://github.com/NNJZSRPC/NNJZSRPC.github.io.git ./NNJZSRPC --depth=1
      - name: ll
        run: |
          ls -a
          pwd
      - name: cd
        run: cd ./NNJZSRPC/
      - name: ll
        run: |
          ls -a
          pwd
      - name: branch
        run: git branch
      - name: ll
        run: |
          ls -a
          pwd
      - name: checkout
        run: git checkout master
      - name: ll
        run: |
          ls -a
          pwd

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: git branch
