name: Update Website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "source" branch
  push:
    branches: [ "source" ]
  pull_request:
    branches: [ "source" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print github.repository
        run: echo ${{ github.repository }}
      - name: Clone repository
        run: |
          git clone https://github.com/${{ github.repository }}.git -b source ./source --depth=1
          git clone https://github.com/${{ github.repository }}.git -b master ./master --depth=1
          git clone https://github.com/${{ github.repository }}.git -b web ./web --depth=1
          git clone https://github.com/NNJZSRPC/hexo-theme-icarus.git ./master/themes/icarus --depth=1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
      - name: Merge Files From Different Branches
        run: |
          # Create source dir
          mkdir -p ./master/source/_posts/
          # Move config files
          mv ./source/_config.yml ./master/_config.yml
          mv ./source/_config.icarus.yml ./master/_config.icarus.yml
          # Delete README.md
          rm ./source/README.md
          # Move /about and /contribute pages
          mv ./source/about ./master/source/
          mv ./source/contribute ./master/source/
          # Move posts
          mv ./source/* ./master/source/_posts/
          # List files
          ls -alR ./master
          ls -alR ./source
      - name: Npm Install
        run: |
          cd ./master/
          npm install
          npm install hexo -g
      - name: Hexo Generate Files
        run: |
          cd ./master
          hexo generate
      - name: Move Generated Files
        run: |
          rm -rf ./web/*
          mv ./master/public/* ./web/
          ls -alR ./web
      - name: Git Commit
        run: |
          cd ./web/
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Auto Update Website"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: web
          directory: ./web/
